name: Schedule Rancher test on openqa.opensuse.org
on:
  push:
    branches:
      - o3_schedule
  schedule:
    - cron:  '0 6 * * MON'
jobs:
  latest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Get most recent image version
        run: |
          git clone https://github.com/rancher/rancher.git
          cd rancher/
          tag=$(git describe --tag $(git rev-list --tags --max-count=1))
          echo $tag
          docker manifest inspect rancher/rancher:$tag >/dev/null
          STATUS=$?
          echo ::set-output name=STATUS::$STATUS
  schedule:
    needs: latest-version
    runs-on: ubuntu-latest
    container: registry.opensuse.org/devel/openqa/containers15.2/openqa_webui:latest
    steps:
      - name: Get latest Tumbleweed published build number
        run: >
          VALUE=`curl -s https://openqa.opensuse.org/group_overview/1.json
          | jq -r '[.build_results[] | select(.tag.description=="published") |
          select(.version=="Tumbleweed") | .build] | sort | reverse | .[0]'`;
          echo ::set-output name=VALUE::$VALUE;
        id: tumbleweedbuildnumber
      - name: Schedule Tumbleweed job
        if: env.STATUS == '0'
        run: >
          openqa-client isos post --apikey ${{ secrets.O3_APIKEY }} --apisecret ${{ secrets.O3_APISECRET }}
          --host "openqa.opensuse.org" DISTRI=opensuse VERSION=Tumbleweed ARCH=x86_64 FLAVOR=DVD-rancher
          HDD_1=opensuse-Tumbleweed-x86_64-${{ steps.tumbleweedbuildnumber.outputs.VALUE }}-Tumbleweed@64bit.qcow2
          BUILD=`date +"%Y%m%d%H%M"`
      - name: Get latest 15.3 published build number
        run: >
          VALUE=`curl -s https://openqa.opensuse.org/group_overview/50.json
          | jq -r '[.build_results[] | select(.tag.description=="published") |
          select(.version=="15.3") | .build] | sort | reverse | .[0]'`;
          echo ::set-output name=VALUE::$VALUE;
        id: leap153buildnumber
     - name: Schedule 15.3 job
       if: env.STATUS == '0'
       run: >
          openqa-client isos post --apikey ${{ secrets.O3_APIKEY }} --apisecret ${{ secrets.O3_APISECRET }}
          --host "openqa.opensuse.org" DISTRI=opensuse VERSION='15.3' ARCH=x86_64 FLAVOR=DVD-rancher
          HDD_1=opensuse-15.3-x86_64-${{ steps.leap153buildnumber.outputs.VALUE }}-gnome@64bit.qcow2
          BUILD=`date +"%Y%m%d%H%M"`

